version: "3.9"

services:  
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db:5432/postgres
      API_URL: https://jsonplaceholder.typicode.com/posts
    volumes:
      - ./scripts:/app/scripts
    command: cron -f

  web:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db:5432/postgres
    volumes:
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    command: uvicorn scripts.dashboard:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
